version: "3.8"

services:
  client:
    build:
      dockerfile: ../Dockerfile
      context: ./myapp
    restart: on-failure
    ports:
      - "$SVE_LOCAL_PORT:$SVE_DOCKER_PORT"
    environment:
      VITE_BACK_URI: http://${HOST_IPV4}:$SPRING_LOCAL_PORT
      VITE_SOCKET_URI: ws://${HOST_IPV4}:$SPRINT_LOCAL_SOCKET_PORT
