version: "3.8"

services:
  client:
    build:
      dockerfile: ../Dockerfile
      context: ./myapp
      args:
        - VBU=http://$HOST_IPV4:$SPRING_LOCAL_PORT
        - VSU=ws://$HOST_IPV4:$SPRING_LOCAL_SOCKET_PORT

    restart: on-failure
    ports:
      - "$SVE_LOCAL_PORT:$SVE_DOCKER_PORT"