version: "3.8"

services:
  client:
    build:
      dockerfile: ../Dockerfile
      context: ./myapp
      args:
        VITE_BACK_URI: http://${HOST_IPV4}:$SPRING_LOCAL_PORT
        VITE_SOCKET_URI: ws://${HOST_IPV4}:$SPRING_LOCAL_SOCKET_PORT

    restart: on-failure
    ports:
      - "$SVE_LOCAL_PORT:$SVE_DOCKER_PORT"